export interface BibleVerse {
  reference: string;
  text: string;
}

export const BIBLE_VERSES: BibleVerse[] = [
  { reference: "1 Tessalonicenses 5:17", text: "Orem sem cessar." },
  { reference: "Romanos 12:12", text: "Perseverem na oração." },
  { reference: "Colossenses 4:2", text: "Dediquem-se à oração, vigiando com gratidão." },
  { reference: "Efésios 6:18", text: "Orem em todo tempo no Espírito." },
  { reference: "Lucas 18:1", text: "Jesus ensinou que devemos orar sempre e nunca desanimar." },
  { reference: "Mateus 26:41", text: "Vigiai e orai para não cair em tentação." },
  { reference: "Marcos 14:38", text: "O espírito está pronto, mas a carne é fraca." },
  { reference: "1 Pedro 4:7", text: "Sejam sóbrios e vigilantes em oração." },
  { reference: "Tiago 5:16", text: "A oração do justo é poderosa e eficaz." },
  { reference: "Mateus 21:22", text: "Tudo o que pedirem em oração, crendo, receberão." },
  { reference: "Marcos 11:24", text: "Creiam que receberam o que pediram em oração." },
  { reference: "João 14:13-14", text: "Jesus promete responder pedidos feitos em Seu nome." },
  { reference: "João 15:7", text: "Permanecer em Cristo fortalece nossas orações." },
  { reference: "João 16:23-24", text: "Peçam em nome de Jesus, para que a alegria seja completa." },
  { reference: "1 João 5:14-15", text: "Deus nos ouve quando pedimos segundo a Sua vontade." },
  { reference: "Jeremias 33:3", text: "Deus convida: clame a Ele e Ele responderá." },
  { reference: "Salmo 50:15", text: "Clame a Deus no dia da angústia." },
  { reference: "Salmo 34:17", text: "O Senhor ouve o clamor dos justos." },
  { reference: "Salmo 18:6", text: "Deus ouve o clamor em meio à aflição." },
  { reference: "Salmo 120:1", text: "Na angústia, clamei ao Senhor, e Ele me ouviu." },
  { reference: "Jonas 2:2", text: "Mesmo no fundo da aflição, Deus ouve a oração." },
  { reference: "Filipenses 4:6-7", text: "Não viva dominado pela ansiedade; leve tudo a Deus em oração, com gratidão, e receba a paz que vem dEle." },
  { reference: "Hebreus 4:16", text: "Aproxime-se de Deus com confiança, porque há graça e socorro disponível." },
  { reference: "2 Crônicas 20:12", text: "Quando não sabemos o que fazer, podemos colocar os olhos em Deus." },
  { reference: "Salmo 65:2", text: "Deus é aquele que ouve a oração." },
  { reference: "Salmo 66:19-20", text: "Deus ouve e atende a voz da oração." },
  { reference: "Salmo 116:1-2", text: "Amo o Senhor, porque Ele ouviu a minha voz." },
  { reference: "Provérbios 15:8", text: "A oração dos retos é prazer para o Senhor." },
  { reference: "Provérbios 15:29", text: "O Senhor ouve a oração dos justos." },
  { reference: "Isaías 65:24", text: "Antes mesmo de clamarem, Deus responde." },
  { reference: "1 Pedro 3:12", text: "Os olhos do Senhor estão sobre os justos, e Seus ouvidos atentos às suas orações." },
  { reference: "Mateus 6:6", text: "O Pai vê em secreto e recompensa." },
  { reference: "Hebreus 11:6", text: "Quem se aproxima de Deus precisa crer que Ele existe e recompensa os que O buscam." },
  { reference: "Tiago 1:5-6", text: "Peça sabedoria a Deus com fé, sem duvidar." },
  { reference: "Mateus 7:7-8", text: "Peça, busque e bata; Deus responde aos que O procuram." },
  { reference: "Lucas 11:9-10", text: "Quem pede recebe, quem busca encontra, quem bate vê a porta se abrir." },
  { reference: "Marcos 9:24", text: "Senhor, eu creio; ajuda-me na minha falta de fé." },
  { reference: "Mateus 17:20", text: "A fé, mesmo pequena como um grão de mostarda, move montanhas." },
  { reference: "João 11:41-42", text: "Jesus agradece ao Pai porque sabe que Ele sempre O ouve." },
  { reference: "1 Timóteo 2:1", text: "Devemos fazer súplicas, orações, intercessões e ações de graças por todos." },
  { reference: "Efésios 1:16-18", text: "Paulo ora para que os cristãos recebam sabedoria e revelação." },
  { reference: "Efésios 3:14-19", text: "Paulo ora para que a igreja seja fortalecida no amor de Cristo." },
  { reference: "Colossenses 1:9-12", text: "Paulo ora para que os irmãos cresçam no conhecimento da vontade de Deus." },
  { reference: "2 Tessalonicenses 1:11-12", text: "Oração para que Deus cumpra Seus propósitos na vida dos irmãos." },
  { reference: "Tiago 5:14-15", text: "Os presbíteros devem orar pelos enfermos." },
  { reference: "Jó 42:10", text: "Deus restaurou Jó enquanto ele orava por seus amigos." },
  { reference: "Números 6:24-26", text: "Bênção sacerdotal: oração de bênção sobre o povo." },
  { reference: "Mateus 6:13", text: "Ore para ser livre do mal." },
  { reference: "Salmo 91:15", text: "Deus responde ao clamor e está conosco na angústia." },
  { reference: "Salmo 141:2", text: "Que a oração suba como incenso diante de Deus." },
  { reference: "2 Tessalonicenses 3:1-3", text: "Orem para que a Palavra avance e para que Deus livre do mal." },
  { reference: "João 17:15", text: "Jesus orou para que o Pai guardasse os discípulos do mal." },
  { reference: "Salmo 5:1-3", text: "Pela manhã, apresente sua oração a Deus e espere com confiança." },
  { reference: "Salmo 17:6", text: "Clame a Deus, pois Ele inclina os ouvidos." },
  { reference: "Salmo 5:3", text: "Pela manhã, apresente sua oração ao Senhor." },
  { reference: "Salmo 63:1", text: "Busque a Deus com sede e desejo profundo." },
  { reference: "Daniel 6:10", text: "Daniel orava três vezes ao dia, mesmo sob ameaça." },
  { reference: "Marcos 1:35", text: "Jesus se retirava de madrugada para orar." },
  { reference: "Lucas 5:16", text: "Jesus se retirava para lugares solitários e orava." },
  { reference: "Lucas 6:12", text: "Jesus passou a noite orando antes de escolher os discípulos." },
  { reference: "Atos 3:1", text: "Pedro e João subiam ao templo na hora da oração." },
  { reference: "Salmo 55:17", text: "De tarde, de manhã e ao meio-dia, o salmista orava." },
  { reference: "2 Crônicas 7:14", text: "Se o povo se humilhar, orar e se converter, Deus ouvirá e sarará a terra." },
  { reference: "Salmo 32:5-6", text: "Confessar o pecado abre caminho para o perdão." },
  { reference: "Salmo 51:1-12", text: "Davi ora por misericórdia, purificação e restauração." },
  { reference: "Daniel 9:3-5", text: "Daniel ora com jejum, confissão e arrependimento." },
  { reference: "Neemias 1:4-11", text: "Neemias ora confessando os pecados do povo." },
  { reference: "Lucas 18:13-14", text: "O publicano ora humildemente: Deus, tem misericórdia de mim." },
  { reference: "Atos 8:22", text: "Arrependa-se e ore ao Senhor." },
  { reference: "1 João 1:9", text: "Deus é fiel e justo para perdoar quando confessamos nossos pecados." },
  { reference: "Mateus 7:7", text: "Peçam, busquem e batam; Deus se revela aos que O procuram." },
  { reference: "Jeremias 29:12-13", text: "Quando vocês clamarem e orarem a Deus, Ele os ouvirá; quando O buscarem de todo o coração, O encontrarão." },
  { reference: "Salmo 34:4", text: "Busquei o Senhor, e Ele me respondeu; livrou-me de todos os meus temores." },
];

export function getRandomVerse(): BibleVerse {
  return BIBLE_VERSES[Math.floor(Math.random() * BIBLE_VERSES.length)];
}
