export const DEFAULT_PRAYER_CATEGORIES = [
  { name: "Family", icon: "home", color: "#e07b2a" },
  { name: "Health & Healing", icon: "heart-pulse", color: "#ef4444" },
  { name: "Work & Career", icon: "briefcase", color: "#3b82f6" },
  { name: "Relationships", icon: "users", color: "#8b5cf6" },
  { name: "Finance", icon: "coins", color: "#22c55e" },
  { name: "Spiritual Growth", icon: "flame", color: "#f59e0b" },
  { name: "Protection", icon: "shield", color: "#64748b" },
  { name: "Wisdom & Guidance", icon: "compass", color: "#06b6d4" },
  { name: "Peace", icon: "leaf", color: "#10b981" },
  { name: "Salvation", icon: "cross", color: "#d97706" },
  { name: "Marriage", icon: "ring", color: "#ec4899" },
  { name: "Children", icon: "baby", color: "#f97316" },
  { name: "Church & Ministry", icon: "church", color: "#7c3aed" },
  { name: "Nation & Government", icon: "landmark", color: "#1d4ed8" },
  { name: "Missions", icon: "globe", color: "#0891b2" },
  { name: "Grief & Loss", icon: "cloud-rain", color: "#475569" },
  { name: "Praise & Thanksgiving", icon: "star", color: "#eab308" },
  { name: "Other", icon: "more-horizontal", color: "#6b7280" },
];
