// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/themes/DarkContrast.tsx": () => import("../components/mockups/themes/DarkContrast.tsx"),
  "./components/mockups/themes/LightTheme.tsx": () => import("../components/mockups/themes/LightTheme.tsx")
};
